web:
  build: .
  command: php -S 0.0.0.0:80 -t /code/wordpress
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - .:/code
db:
  image: orchardup/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: wordpress